version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run: echo "A first hello"
  deploy-staging:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            sudo apt-get -y -qq update
            sudo pip install awscli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            echo "[default]" >> ~/.aws/config
            echo "region = ap-northeast-1" >> ~/.aws/config
      - run:
          name: Deploy to S3
          command: aws deploy push --application-name prtest --s3-location s3://deploy.billing.bucket/revision/staging/prtest.zip --source .
      - run:
          name: Create deployment on CodeDeoploy
          command: aws deploy create-deployment --application-name prtest --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --description "My demo deployment" --s3-location bucket=deploy.billing.bucket,bundleType=zip,key=revision/staging/prtest.zip
  deploy-prduction:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            sudo apt-get -y -qq update
            sudo pip install awscli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            echo "[default]" >> ~/.aws/config
            echo "region = ap-northeast-1" >> ~/.aws/config
      - run:
          name: Deploy to S3
          command: aws deploy push --application-name prtest --s3-location s3://deploy.billing.bucket/revision/production/prtest.zip --source .
      - run:
          name: Create deployment on CodeDeoploy
          command: aws deploy create-deployment --application-name prtest --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --description "My demo deployment" --s3-location bucket=deploy.billing.bucket,bundleType=zip,key=revision/production/prtest.zip

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production
