version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
deployment:
  staging:
    branch: master
    codedeploy:
      prtest:
        application_root: /
        region: ap-northeast-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: deploy.billing.bucket
            key_pattern: prtest-{BRANCH}-{SHORT_COMMIT}
        deployment_group: staging
