version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/working_directory
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Install python
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
      - run:
          name: Install pip
          command: curl -O https://bootstrap.pypa.io/get-pip.py
      - run:
          name: Install awscli
          command: pip install awscli --upgrade --user
      - run:
          name: Deploy to S3
          command: aws deploy push --application-name prtest --s3-location s3://deploy.billing.bucket/revision/staging/prtest.zip --source .
      - run:
          name: Create deployment on CodeDeoploy
          command: aws deploy create-deployment --application-name prtest --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --description "My demo deployment" --s3-location bucket=deploy.billing.bucket,bundleType=zip,key=revision/staging/prtest.zip

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#         requires:
#           - build
#         filters:
#           branches:
#             only: master
# apt-get -y -qq update
# apt-get -y -qq install awscli
# pip install awscli --upgrade --user
            # sudo apt-get -y -qq install python3.4-dev
            # sudo curl -O https://bootstrap.pypa.io/get-pip.py
            # sudo python3.4 get-pip.py --user
