version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run: echo "A first hello"
  deploy-staging:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            sudo apt-get -y -qq update
            sudo pip install awscli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            echo "[default]" >> ~/.aws/config
            echo "region = ap-northeast-1" >> ~/.aws/config
      - run:
          name: Create deployment on CodeDeoploy
          command: aws deploy create-deployment --application-name prtest --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --description "My demo deployment" --github-location commitId=$CIRCLE_SHA1,repository=awwa/prtest
  deploy-production:
    docker:
      - image: circleci/python:3.6.4-node-browsers
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            sudo apt-get -y -qq update
            sudo pip install awscli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            echo "[default]" >> ~/.aws/config
            echo "region = ap-northeast-1" >> ~/.aws/config
      - run:
          name: Create deployment on CodeDeoploy
          command: aws deploy create-deployment --application-name prtest --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --description "My demo deployment" --github-location commitId=$CIRCLE_SHA1,repository=awwa/prtest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production
